### ISSUE TITLE
No path separator on start up

### ISSUE THREAD

**Issue by davidtoop** [Dyalog/MiServer#28]
You need to add a path separator after line 44 of Start something like: dyalog,←('/'≠¯1↑dyalog)/'/'

Running on raspberry Pi

**Comment by bpbecker** [comment]
Thanks for catching this!  It seems that the DYALOG environment variable has a trailing file separator character in Windows, but not in Unix-based platforms and a recent change to Start got tripped up this.  It's been fixed and committed to the repository.
