### ISSUE TITLE
Starting MS3 sample site fails when MiServer is installed into a directory with spaces in the directory path

### ISSUE THREAD

**Issue by arcfide** [Dyalog/MiServer#64]
If you have a folder with spaces in the path, then starting the sample MS3 site doesn't work.

**Comment by bpbecker** [comment]
Are you sure you have a current build? This was fixed years ago.  

I'm running Dyalog 64 Unicode v16.0.
To verify I...
1. downloaded latest zip file from the master branch. 
2. Unzipped to to c:\tmp\miserver master\ (note the space)
3. Started Dyalog APL
4. )load "c:\tmp\miserver master\miserver.dws"
5. Start './MS3'
And things work just fine.

What environment are you running in?

**Comment by arcfide** [comment]
I just grabbed the latest release. Is there a newer release around?

**Comment by bpbecker** [comment]
There's a new release in the works... for the meantime, grab the latest commit from the master branch.

**Comment by bpbecker** [comment]
Oops.... didn't mean to click "close and comment", just "comment"...

**Comment by bpbecker** [comment]
Cool!  Thanks!  Take care.
