### ISSUE TITLE
MiServer 3.0.1539  Compose vs Render and _Request.GetData

### ISSUE THREAD

**Issue by RayCannon** [Dyalog/MiServer#66]
At Brian request I am reporting this as an issue rather than in the MiServer forum.

Having updated from MiServer 3.0  (mine was dated 16/11/2016) to 3.0.1539 I am having a lot of problems. 

For a start HandleMSP on line 150 calls my function Compose, but then on line 179 call Render.
Under the old MiServer,  HandleMSP called Compose only on line 170, and did not call Render at all.

Compose or Render, which should be being used?

In addition, under 3.0.1539,  when attempting to read event information (when an option was selected on a drop down box),
    what←_Request.GetData'_what'
    selected←_Request.GetData what
"selected" is an empty string, while under the old MiServer it had the value of the item selected.
As a result, my code is failing to respond to items selected in the drop down boxes.

I am unsure if these two issues are related.

How upward compatible should MiServe be, or do I need to rewrite my (old code) every time MiServer is (or Dyalog) is updated?

Ray Cannon

**Comment by bpbecker** [comment]
Hi Ray,

Unless you're doing something strange, MiServer 3 is highly upward compatible.  As far as I can recall, we never had to rewrite any of the MiServer 3 samples as we introduced new versions of MiServer. We did make some fundamental, and breaking, changes when moving from MiServer 2 to 3.  One of those changes was changing the name of the method your page should use from Render to Compose.  This made sense both linguistically and syntactically.  Your page composes the content by adding elements.  Render is used internally by the MiPage class and is executed to render the final output from content you've added.

As for retrieving values, MiServer makes it easy...
First, if you have public fields in your page with the same name as an input control, MiServer will move the values of those controls into the corresponding public fields.  This works for either submitted forms or APLJax callbacks.

#### Submitted Form Example
```
:Class index : #.MiPage

    :Field Public Name←''   
    :Field Public Country←''

    ∇ Compose;f;ig
      :Access public
      :If 'get'≡_Request.Method  ⍝ initialize?  (submit uses the 'post' method')
          f←Add _.Form           ⍝ add a form (_.Form is the Dyalog enhanced version of HTML's form element)
          ig←f.Add _.InputGrid   ⍝ InputGrid is Dyalog's control for formatting labels and inputs
          ig.Inputs←('Name'New _.Input)('Country'New _.Select'UK' 'USA' 'DK' 'DE') ⍝ a text input and a select box
          ig.Labels←'Name:' 'Country:' ⍝ labels
          f.Add _.br                   ⍝ line break
          f.Add _.SubmitButton'OK'     ⍝ submit button
      :Else
          Add'Welcome ',Name,' from ',Country,'!'  ⍝ the page content is now our friendly message
      :EndIf
    ∇
:EndClass
```
#### APLJax Example
```
:Class index : #.MiPage

    :Field Public Name←''
    :Field Public Country←''

    ∇ Compose;f;ig
      :Access public
      f←Add _.Form           ⍝ add a form (_.Form is the Dyalog enhanced version of HTML's form element)
      ig←f.Add _.InputGrid   ⍝ InputGrid is Dyalog's control for formatting labels and inputs
      ig.Inputs←('Name'New _.Input)('Country'New _.Select'UK' 'USA' 'DK' 'DE') ⍝ a text input and a select box
      ig.Labels←'Name:' 'Country:' ⍝ labels
      f.Add _.br                   ⍝ line break
      (f.Add _.Button'OK').On'click' 'Welcome'     ⍝ swhen button is clicked, call Welcome
    ∇

    ∇ r←Welcome
      :Access public
      r←'body'Replace'Welcome ',Name,' from ',Country,'!'
    ∇
:EndClass
```
If you're not using public fields, you can always use the Get method to retrieve the values by name.
```
:Class index : #.MiPage
    ∇ Compose;f;ig
      :Access public
      f←Add _.Form           ⍝ add a form (_.Form is the Dyalog enhanced version of HTML's form element)
      ig←f.Add _.InputGrid   ⍝ InputGrid is Dyalog's control for formatting labels and inputs
      ig.Inputs←('Name'New _.Input)('Country'New _.Select'UK' 'USA' 'DK' 'DE') ⍝ a text input and a select box
      ig.Labels←'Name:' 'Country:' ⍝ labels
      f.Add _.br                   ⍝ line break
      (f.Add _.Button'OK').On'click' 'Welcome'     ⍝ submit button
    ∇

    ∇ r←Welcome
      :Access public
      r←'body'Replace'Welcome ',(Get 'Name'),' from ',(Get 'Country'),'!'
    ∇

:EndClass
```
I hope this helps.
